name: saiskarFood
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^2.1.0
  get: ^4.1.4
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  fluttericon: ^2.0.0
  google_maps_flutter: ^2.2.0
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  permission_handler: ^9.2.0
  url_strategy: ^0.2.0
  flutter_typeahead: ^3.1.3
  google_maps_flutter_web: ^0.5.1
  flutter_google_places: ^0.3.0
  http: ^0.13.5
  flutter_svg: ^1.1.6
  webview_flutter: ^2.0.9
  firebase_core: ^1.2.1
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.1.5
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
