name: restaurantApp
description: Fast food shop app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  intl: ^0.20.2
  http: ^1.4.0
  dots_indicator: ^4.0.1
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.12.1
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  #url_strategy: ^0.2.0
  flutter_typeahead: ^5.2.0
  google_maps_flutter_web: ^0.5.12
  #flutter_google_places: ^0.3.0
  flutter_svg: ^2.1.0
  webview_flutter: ^4.11.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  #flutter_local_notifications: ^19.1.0
  
  #ICONS
  fluttericon: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/