// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcTmSQ8CP7Gke4JElebeWly6xU_9kZR8E',
    appId: '1:78543721179:web:ed90b0567f546bae8c32fe',
    messagingSenderId: '78543721179',
    projectId: 'appdelivery-370904',
    authDomain: 'appdelivery-370904.firebaseapp.com',
    storageBucket: 'appdelivery-370904.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbv512LubpsJBIO0g4KSIrHdu3X1dZXQ',
    appId: '1:78543721179:android:a9e9820d7a3604538c32fe',
    messagingSenderId: '78543721179',
    projectId: 'appdelivery-370904',
    storageBucket: 'appdelivery-370904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCAn5Gesj7eKH17Pjw6Ed9cZ6aXc-R7G0',
    appId: '1:78543721179:ios:3668b73e021ff6478c32fe',
    messagingSenderId: '78543721179',
    projectId: 'appdelivery-370904',
    storageBucket: 'appdelivery-370904.appspot.com',
    iosClientId: '78543721179-ma31vg5j8u0noidf5rmv9hk4v6dfl6m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTiendaComida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCAn5Gesj7eKH17Pjw6Ed9cZ6aXc-R7G0',
    appId: '1:78543721179:ios:3668b73e021ff6478c32fe',
    messagingSenderId: '78543721179',
    projectId: 'appdelivery-370904',
    storageBucket: 'appdelivery-370904.appspot.com',
    iosClientId: '78543721179-ma31vg5j8u0noidf5rmv9hk4v6dfl6m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTiendaComida',
  );
}
